Repository micronaut-projects/micronaut-jackson-xml, pull requests merged in 2020-09, with the labels that each got.

#46 doc: add release history
  src/main/docs/guide/releaseHistory.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#47 set githubCoreBranch to 2.0.x
  gradle.properties
Labels: relates-to: build

#43 [jackson-xml] Update common files for branch master
  .github/workflows/release-notes.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#48 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade
